# Generated by Django 4.0.3 on 2022-05-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kniha',
            name='autor',
            field=models.CharField(default='Neznámý', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kniha',
            name='recenze',
            field=models.TextField(default='Nic o ní nevíme'),
            preserve_default=False,
        ),
    ]
