# Generated by Django 4.0.3 on 2022-05-23 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihy', '0002_kniha_autor_kniha_recenze'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kniha',
            options={'verbose_name_plural': 'Knihy'},
        ),
        migrations.AddField(
            model_name='kniha',
            name='release',
            field=models.DateField(default=datetime.datetime(2022, 5, 23, 18, 58, 37, 16207)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kniha',
            name='jmeno',
            field=models.CharField(max_length=20),
        ),
    ]
