# Generated by Django 4.0.3 on 2022-05-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihy', '0003_alter_kniha_options_kniha_release_alter_kniha_jmeno'),
    ]

    operations = [
        migrations.AddField(
            model_name='kniha',
            name='heslo',
            field=models.CharField(default='pes', max_length=30),
            preserve_default=False,
        ),
    ]
